[package]
name = "pw-hassgen"
version = "0.1.2"
edition = "2021"

[profile.release]
strip = true

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9.34"
sqlx = { version = "0.8.3", default-features = false, features = [
    "postgres",
    "runtime-tokio",
    "macros",
] }
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
