[package]
name = "pw-hassgen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = "0.9.29"
sqlx = { version = "0.7.3", default-features = false, features = [
    "postgres",
    "runtime-tokio",
    "macros",
] }
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros"] }
